### ISSUE TITLE
データの取得に失敗することがある

### ISSUE THREAD

**Issue by elecdeer** [elecdeer/resas-population-visualization#22]
Vercelに上げたときのみ？

```
{}
useCache: https://opendata.resas-portal.go.jp/api/v1/prefectures
2022-03-22T17:59:28.164Z	517da379-9f41-40f9-97d7-286a4e580343	ERROR	error at /population ZodError: [
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "result"
    ],
    "message": "Required"
  }
]
    at handleResult (file:///var/task/node_modules/zod/lib/index.mjs:430:23)
    at ZodObject.safeParse (file:///var/task/node_modules/zod/lib/index.mjs:543:16)
    at ZodObject.parse (file:///var/task/node_modules/zod/lib/index.mjs:522:29)
    at fetchResasPrefectures (/var/task/.next/server/pages/api/prefectures.js:50:116)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async handler (/var/task/.next/server/pages/api/prefectures.js:102:24)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:182:9)
    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:386:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/base-server.js:488:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:228:32) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'array',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    }
  ],
  format: [Function (anonymous)],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)]
}
```

**Comment by elecdeer** [comment]
ログを追加して様子を見る
